name: 'Scheduled sync to release branch'

on:
  # Allow manual syncing/testing.
  workflow_dispatch:
  # Every Monday at 0600 UTC.
  schedule:
    - cron: '0 6 * * 1'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Check out develop branch
        uses: actions/checkout@v3
        with:
          # uses the `khan-actions-bot` Khan Org level user which was granted
          # permissions to override branch protections.
          token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
          ref: develop
      - name: Check out release branch
        uses: actions/checkout@v3
        with:
          # uses the `khan-actions-bot` Khan Org level user which was granted
          # permissions to override branch protections.
          token: ${{ secrets.KHAN_ACTIONS_BOT_TOKEN }}
          ref: workflow-testing
      - name: Merge develop into release
        run: |
          git config --global user.name 'khan-actions-bot'
          git config --global user.email 'infrastructure-data@khanacademy.org'
          
          git merge origin/develop --no-edit --allow-unrelated-histories -m 'Merge develop into workflow-testing branch ${{github.job}} in run id ${{github.run_id}}'
      - name: Notify Slack on failure
        uses: ./.github/actions/notify_slack
